export default [
  {
    id: 1,
    title: 'iPhone 9',
    price: 549,
    discountPercentage: 12.96,
    brand: 'Apple',
    category: 'smartphones',
    amount: 2,
    image: 'https://cdn.dummyjson.com/product-images/1/1.jpg',
  },
  {
    id: 2,
    title: 'iPhone X',
    price: 899,
    discountPercentage: 17.94,
    brand: 'Apple',
    category: 'smartphones',
    amount: 1,
    image: 'https://cdn.dummyjson.com/product-images/2/1.jpg',
  },
  {
    id: 3,
    title: 'Samsung Universe 9',
    price: 1249,
    discountPercentage: 15.46,
    brand: 'Samsung',
    category: 'smartphones',
    amount: 1,
    image: 'https://cdn.dummyjson.com/product-images/3/1.jpg',
  },
  {
    id: 4,
    title: 'OPPOF19',
    price: 280,
    discountPercentage: 17.91,
    brand: 'OPPO',
    category: 'smartphones',
    amount: 1,
    image: 'https://cdn.dummyjson.com/product-images/4/1.jpg',
  },
  {
    id: 5,
    title: 'Huawei P30',

    price: 499,
    discountPercentage: 10.58,

    brand: 'Huawei',
    category: 'smartphones',
    amount: 1,
    image: 'https://cdn.dummyjson.com/product-images/5/1.jpg',
  },
];
